name: flutter_firebase_auth
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  freezed_annotation: ^2.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  go_router: ^6.5.5 
  equatable: ^2.0.3
  google_sign_in: ^6.1.0
  firebase_core_web: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true